spring:
  profiles:
    active: postgres
  data:
    rest:
      base-path: /api
  batch:
    job:
      names: ${job.name:NONE}   #--job.name=jdbcCursorItemReaderJob
---
spring:
  profiles: postgres
  datasource:
    hikari:
      maximum-pool-size: 4
    password: pgadmin
    url: jdbc:postgresql://db.deogi:5432/postgres
    username: pgadmin
  jpa:
    hibernate.ddl-auto: create
    #  show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.default_batch_fetch_size: 1000
  #    hibernate.format_sql: true
---
spring:
  profiles: h2
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:spring-batch #In-memory
      #jdbc-url: jdbc:h2:file:./spring-boot-batch-in-action/data/spring-batch;AUTO_SERVER=TRUE; #File-based
      username: sa
      password:
    h2:
      console:
        enables: true
        path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect